#!/usr/local/bin/zsh

# Ensure ZSH environment is loaded
source ~/.zshrc

# JavaScript
if [ -e yarn.lock ] || [ -e package.json ]; then
  yarn install
fi

# Ruby
if [ -e Gemfile ]; then
  bundle install -j `sysctl -n hw.ncpu`
fi
