#!/usr/bin/env zsh

# Ensure ZSH environment is loaded
source ~/.zshrc

source $(dirname $0)/update-dependencies

if [ -f .git/hooks/post-merge ]; then
  echo "Running local post-checkout hook"
  .git/hooks/post-checkout $@
fi
