#!/usr/bin/env zsh

source $(dirname $0)/shared-functions

# Only run out custom stuff inside project root
if [[ "$PWD/" = $HOME/src/* ]]; then
  # JavaScript
    if  [ -e yarn.lock ]; then; denvig install;
  elif [[ -e pnpm-lock.yaml || -e pnpm-lock.yml ]]; then; denvig install;
  elif  [ -e package-lock.json ]; then; denvig install;
  fi

  # Ruby
  if [ -e Gemfile ]; then bundle_install; fi
  if [ -e backend/Gemfile ]; then (cd backend; bundle_install); fi
fi
