#!/usr/local/bin/zsh

source $(dirname $0)/shared-functions

# Only run out custom stuff inside project root
if [[ "$PWD/" = $HOME/src/* ]]; then
  # JavaScript
  if [ -e yarn.lock ] || [ -e package.json ]; then; yarn_install; fi

  # Ruby
  if [ -e Gemfile ]; then bundle_install; fi
fi
