tap "heroku/brew"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "mongodb/brew"
brew "autoconf"
brew "automake"
brew "awscli"
brew "certbot"
brew "cfssl"
brew 'cmake'
brew "direnv"
brew "dnsmasq", restart_service: false
brew "glib"
brew "gcc@5"
brew "git"
brew "libxml2"
brew "gettext"
brew "gnutls"
brew "gnupg"
brew "goenv"
brew "gpg2"
brew "heroku/brew/heroku"
brew "hub"
brew "jpeg"
brew "jq"
brew "libevent"
brew "libffi"
brew "libmpc"
brew "libtool"
brew "libyaml"
brew "mailhog", restart_service: false
brew "mongodb-community"
brew "mas"
brew "nginx", restart_service: false
brew "node"
brew "node-build"
brew "nodenv"
brew "openssl"
brew "pinentry-mac"
brew "postgresql", restart_service: false
brew "pyenv"
brew "redis", restart_service: false
brew "rbenv"
brew "rbenv-default-gems"
brew "ruby-build"
brew "s3cmd"
brew "terraform"
brew "tig"
brew "wget"
brew "zsh"
cask "cyberduck"
cask "github"
cask "visual-studio-code"
cask "xquartz"
mas "Keynote", id: 409183694
mas "Moom", id: 419330170
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
