#!/usr/local/bin/zsh

DOTFILES_DIR=$(cd "$(dirname $0)/.."; pwd)
cd $DOTFILES_DIR

source $DOTFILES_DIR/script/.shared
out "dotfiles/script/setup"

echo ""
symlink_dotfile Brewfile
symlink_dotfile gitconfig
symlink_dotfile gitconfig-user
symlink_dotfile gitignore-global
symlink_dotfile zshrc
symlink_dotfile zsh
symlink_dotfile rbenv/default-gems

echo ""
symlink "$DOTFILES_DIR/etc/dnsmasq.conf" "/usr/local/etc/dnsmasq.conf"
symlink "$DOTFILES_DIR/etc/nginx/nginx.conf" "/usr/local/etc/nginx/nginx.conf"
symlink "$DOTFILES_DIR/etc/nginx/server_defaults" "/usr/local/etc/nginx/server_defaults"
symlink "$DOTFILES_DIR/etc/nginx/public" "/usr/local/etc/nginx/public"
symlink "$DOTFILES_DIR/etc/redis.conf" "/usr/local/etc/redis.conf"

echo ""
symlink ~/Library/Mobile\ Documents/com\~apple\~CloudDocs ~/iCloud\ Drive
