#!/usr/local/bin/zsh

DOTFILES_DIR=$(cd "$(dirname $0)/.."; pwd)
cd $DOTFILES_DIR

source $DOTFILES_DIR/script/.shared
out "dotfiles/script/setup"

# Apply MacOS defaults
echo ""
run "sh $DOTFILES_DIR/macos/defaults.sh"

echo ""
symlink_dotfile Brewfile
symlink_dotfile gitconfig
symlink_dotfile gitignore-global
symlink_dotfile zshrc
symlink_dotfile zsh
symlink_dotfile rbenv/default-gems
symlink_dotfile gemrc
symlink_dotfile editorconfig
symlink_dotfile eslintrc.json
symlink_dotfile tigrc
symlink_dotfile gnupg/gpg.conf
symlink_dotfile gnupg/gpg-agent.conf

echo ""
symlink_dotfile_force hyper.js # hyper keeps writing it back instantly

echo ""
symlink "$DOTFILES_DIR/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
symlink "$DOTFILES_DIR/tslint.json" "$HOME/tslint.json"
symlink "$DOTFILES_DIR/etc/dnsmasq.conf" "/usr/local/etc/dnsmasq.conf"
symlink "$DOTFILES_DIR/etc/nginx/server_defaults" "/usr/local/etc/nginx/server_defaults"
symlink "$DOTFILES_DIR/etc/nginx/public" "/usr/local/etc/nginx/public"
symlink "$DOTFILES_DIR/etc/redis.conf" "/usr/local/etc/redis.conf"
symlink "$DOTFILES_DIR/macos/quick-actions/copy-path" "$HOME/Library/Services/copy-path.workflow"

echo ""
symlink ~/Library/Mobile\ Documents/com\~apple\~CloudDocs ~/iCloud\ Drive

# Nginx is templated, so we need to replace vars
echo ""
NGINX_CONFIG=$(cat $DOTFILES_DIR/etc/nginx/nginx.conf)
NGINX_CONFIG=${NGINX_CONFIG//\$\{USER\}/$USER}
NGINX_CONFIG=${NGINX_CONFIG//\$\{HOME\}/$HOME}
NGINX_CONFIG=${NGINX_CONFIG//\$\{NPROC\}/$(sysctl hw.physicalcpu | awk '{print $2}')}
echo $NGINX_CONFIG > /usr/local/etc/nginx/nginx.conf
out "configured /usr/local/etc/nginx/nginx.conf"

# Permissions
chmod -R 700 ~/.gnupg
