#!/usr/bin/env zsh

# warn if brew is not available
if ! command -v brew &> /dev/null; then
  echo "Homebrew is not installed. Install via https://brew.sh"
  exit 1
fi

brew install git
brew install zsh

script/bootstrap
