#!/bin/sh

DOTFILES_DIR=$(cd "$(dirname $0)/.."; pwd)
cd $DOTFILES_DIR

source $DOTFILES_DIR/script/.shared
out "dotfiles/script/setup"

echo ""
symlink_dotfile "zshrc"
symlink_dotfile "gitconfig"
symlink_dotfile "gitconfig-user"
symlink_dotfile "gitignore-global"

echo ""
run "ln -fs ~/Library/Mobile\ Documents/com\~apple\~CloudDocs ~/iCloud\ Drive"
