#!/usr/local/bin/zsh

DOTFILES_DIR=$(cd "$(dirname $0)/.."; pwd)
cd $DOTFILES_DIR

source $DOTFILES_DIR/script/.shared
out "dotfiles/script/update"

run "git pull --rebase"

# script/setup should be idempotent
echo ""
script/setup
